services:
  wickedyoda-helper:
    image: ghcr.io/wickedyoda/wickedyodadiscordbot:latest
    pull_policy: always
    container_name: wickedyoda-little-helper
    env_file:
      - env.env
    ports:
      - "8081:8081"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped
