"""Extended fun data for WickedYoda bot.

These lists expand on the hardcoded data in bot.py (which has only 5-9 items
each). This module provides 50+ items per category for much more variety.
"""

# --- Yoda Wisdom (expanded from 9 to 50) ---
YODA_WISDOM_EXTENDED = (
    "Patience you must have, my young Discord user.",
    "Rushed commands, buggy results make.",
    "Helpful the small bot is, yes.",
    "Questions, I sense you have. Answers, I do not.",
    "Judge me by my size, do you? Hmm.",
    "Do or do not, there is no try.",
    "Truly wonderful the mind of a confused user is.",
    "Fear leads to the dark side of the force.",
    "Always in motion, the future is.",
    "A Jedi uses the Force for knowledge and defense, never for attack.",
    "Difficult to see, the dark side is.",
    "I find your lack of faith disturbing.",
    "The ability to speak does not make you intelligent.",
    "I've been waiting for you, Obi-Wan. We meet again, at last.",
    "The Force is strong with this one.",
    "Mmm, these aren't the droids you're looking for.",
    "Foolishness, it is. To the dark side, it leads.",
    "Size matters not, for the Force is with you.",
    "The greatest teacher, failure is.",
    "Much to learn, you still have.",
    "Powerful you have become, the dark side, I sense in you.",
    "Patience, my green friend. Patience.",
    "The greatest trick the Dark Side ever pulled was convincing the galaxy it didn't exist.",
    "A Jedi's strength flows from the Force, not from anger.",
    "Always pass on what you have learned. Give off, you must.",
    "The Force will be with you. Always.",
    "Control, control, you must learn control! If you end up like your dad, a mass murderer, I shall be forced to intervene.",
    "If you will not be turned, you will be destroyed!",
    "The ability to destroy a planet is insignificant next to the power of the Force.",
    "I've been waiting for you, Obi-Wan. We meet again, at last.",
    "Help you? I'm afraid I cannot, Master.",
    "Mmm, forbidden knowledge you seek. Dangerous it is.",
    "The past is the key to the future, my friend.",
    "A journey of a thousand parsecs begins with a single jump.",
    "Much to learn you still have. This is the greatest teacher, the Force is.",
    "The strongest stars are they who are willing to look at the darkness in themselves.",
    "Patience, master. The dark side waits for no one.",
    "A master who can't admit mistakes is a master who has made them.",
    "Hope is the greatest gift of a Jedi's heart.",
    "The weight of the past, it cannot carry you forward.",
    "To be a Jedi is to be a guardian of peace.",
    "The Force speaks in mysteries, young one.",
    "Trust in the Force you must, but question it always.",
    "A lesson learned is worth a thousand victories.",
    "Even the smallest of beings can change the course of the future.",
    "Courage is not the absence of fear, but the mastery of it.",
    "The path to the dark side is through anger, but the path to light is through compassion.",
    "A true master knows when to speak and when to listen.",
    "The greatest victory is to know when to yield.",
    "Fear leads to hate, but hope leads to freedom.",
)

# --- Playful Roasts (expanded from 6 to 50) ---
PLAYFUL_ROASTS_EXTENDED = (
    "Your Wi-Fi probably disconnects just to get a break from you.",
    "If overthinking were a sport, you'd still somehow miss the playoffs.",
    "Your logic is so circular, it makes a roundabout jealous.",
    "You're the reason the word 'dysfunctional' was invented.",
    "Your brain called — it wants a refund for the empty box it got.",
    "You're like a participation trophy in a race nobody signed up for.",
    "If I had a face like yours, I'd sue my parents' faces for damages.",
    "Your personality is so charming, it's like watching a bag of stale chips.",
    "You're the human equivalent of a participation ribbon.",
    "Your sense of self-awareness called — it's still on hold from 2003.",
    "You have the charisma of a wet paper bag and the charm of a tax audit.",
    "Your brain is like a database with 0% storage — completely empty.",
    "You're so indecisive, even the wind can't decide which way to blow.",
    "Your IQ is so low, elevator music seems intellectual.",
    "You bring so much joy to every room you don't enter.",
    "Your personality is like a participation ribbon — everyone gets one but nobody wants it.",
    "You're so socially awkward, even your shadow avoids you at parties.",
    "You're like a dictionary — you're full of words but no one wants to read you.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "Your sense of direction is so bad, you'd get lost in a mirror maze.",
    "You're so forgettable, even your reflection keeps asking who you are.",
    "Your conversational skills are like a broken record — they just repeat and skip.",
    "You're so awkward that even your reflection apologizes when you walk past it.",
    "Your personality is like a blank piece of paper — even it gives up on you.",
    "You're so boring, even the dictionary is tired of looking at you.",
    "Your brain has the memory capacity of a wet napkin.",
    "You're so slow, the fast/slow sign on the highway asks you for directions.",
    "Your problem-solving skills are so bad, you get stuck on the 'pull' door for 10 minutes.",
    "You're so confused, even the GPS gave up and said 'recalculating' in a different language.",
    "Your fashion sense is so bad, the mirror filed a restraining order.",
    "You're so lazy, even procrastination gives up and says 'just do it'.",
    "Your dance moves are so bad, the music files a complaint report.",
    "You're so awkward that even Siri says 'I don't understand' and hangs up.",
    "Your cooking is so bad, the smoke alarm files for emotional damages.",
    "You're so pale, you make vampire skin look tanned.",
    "Your sense of humor is so dry, the Sahara looks like a swamp.",
    "You're so generic, even a random number generator has more personality.",
    "Your memory is so bad, you forget what you were going to say while saying it.",
    "You're so uncoordinated, you trip over your own shadow.",
    "Your problem is that you're proof that even the best things can fail catastrophically.",
    "You're so dense, light bends around you.",
    "Your personality is like a participation trophy — nice to look at but useless.",
    "You're so predictable, the plot twist in your life story is 'you wake up'.",
    "Your logic is so twisted, it makes a pretzel look straight.",
    "You're so socially awkward that even your mirror avoids eye contact.",
    "Your fashion sense is so bad, the clothes rebel and run away.",
    "You're so forgettable that even your own shadow gets confused about which body to follow.",
    "Your brain is like a browser with 1000 tabs open and 998 are crashed.",
    "You're so slow that Netflix asks you to 'Are you still watching?' just by standing still.",
    "Your personality is like a participation badge — everyone has one but nobody admires it.",
)

# --- Compliments (expanded from 6 to 50) ---
COMPLIMENTS_EXTENDED = (
    "You make the server better just by being active in it.",
    "You have strong main-character energy, in a good way.",
    "Your presence lights up even the most mundane text channels.",
    "You're the kind of person who makes everyone feel seen and heard.",
    "Your positive energy is contagious — I'm catching it right now.",
    "You have a gift for making even the most complex topics easy to understand.",
    "Your creativity is genuinely inspiring. The world needs more of that.",
    "You're the reason why side characters in other people's stories wish they were the protagonist.",
    "Your sense of humor is like a perfectly timed GIF — always on point.",
    "You're so consistently kind, I'm starting to think you're a bot programmed to be nice.",
    "Your ability to turn a bad day around with just a message is a superpower.",
    "You have the rare ability to make everyone feel like they're the only person in the room — in a good way.",
    "Your positive attitude is like a warm cup of tea on a rainy day.",
    "You're the human equivalent of a perfectly brewed cup of coffee — always just what's needed.",
    "Your enthusiasm is infectious and makes every conversation feel electric.",
    "You have a way of making the impossible seem effortless.",
    "Your kindness doesn't go unnoticed — it creates ripples that you'll never see.",
    "You're so genuine, even your shadow is impressed.",
    "Your insight is like a lighthouse in a fog — guiding and illuminating.",
    "You have the kind of personality that makes strangers feel like old friends.",
    "Your sense of style is so good, fashion magazines ask for your autograph.",
    "You're the kind of person who makes the world a little brighter just by existing.",
    "Your problem-solving skills are so sharp, they could cut through steel.",
    "You have a way of making everything better just by being in it.",
    "Your laugh is the kind that makes everyone around you smile.",
    "You're so charismatic, even the bots want to be like you.",
    "Your positive outlook is the kind that makes others want to be better people.",
    "You have the kind of mind that could solve world hunger, but you choose to make jokes instead.",
    "Your creativity knows no bounds — it's like watching a master painter at work.",
    "You're so kind-hearted, even the grumpiest person would smile at you.",
    "Your attention to detail is so impressive, even the NSA wants to know your secrets.",
    "You have a way of making everyone feel important — because you do.",
    "Your positive energy is like a battery that never runs out.",
    "You're the kind of person who makes every conversation feel meaningful.",
    "Your sense of humor is so sharp, it could cut through steel.",
    "You have the kind of personality that makes people believe in humanity again.",
    "Your generosity is so genuine, it puts Santa to shame.",
    "You're so effortlessly cool, even James Bond asks for fashion tips.",
    "Your intelligence is so impressive, even Einstein would be jealous.",
    "You have the kind of heart that makes the world a better place.",
    "Your positive attitude is so inspiring, it should come with a warning label.",
    "You're so good at making people laugh, even the dictionary is cracking up.",
    "Your creativity is so vivid, even Picasso would be jealous.",
    "You have the kind of soul that makes angels jealous.",
    "Your kindness is so bright, it could light up the darkest of days.",
    "You're so naturally talented, even talent is jealous of you.",
    "Your positive energy is so powerful, it should be harnessed for renewable energy.",
    "You have the kind of spirit that makes the impossible seem possible.",
    "Your sense of humor is so infectious, even the grumpy cat would crack a smile.",
    "You're so genuinely awesome, even your reflection is impressed.",
)

# --- Would You Rather (expanded from 5 to 50) ---
WOULD_YOU_RATHER_EXTENDED = (
    "Would you rather always be 10 minutes early or always have perfect Wi-Fi?",
    "Would you rather only communicate in GIFs or only in voice notes?",
    "Would you rather have unlimited snacks or unlimited battery life?",
    "Would you rather be able to speak every language or be able to talk to animals?",
    "Would you rather have a rewind button for your life or a pause button?",
    "Would you rather always be 10 degrees too cold or 10 degrees too hot?",
    "Would you rather fight one horse-sized duck or 100 duck-sized horses?",
    "Would you rather have the ability to freeze time or the ability to see through walls?",
    "Would you rather be stuck in a loop of your worst day or never have a good day again?",
    "Would you rather have a million dollars but lose all memories of your loved ones, or $10 but keep all memories?",
    "Would you rather live in a world where everyone can read minds or everyone lies?",
    "Would you rather be famous for something you hate or unknown for something you love?",
    "Would you rather have the power to heal anyone or the power to know when someone will die?",
    "Would you rather never use social media again or never watch TV again?",
    "Would you rather be able to teleport anywhere or be able to read minds?",
    "Would you rather live without the internet or without air conditioning?",
    "Would you rather have a pet dragon or a pet phoenix?",
    "Would you rather be 5'2\" for the rest of your life or 6'5\"?",
    "Would you rather have a lifetime supply of your favorite food or a lifetime supply of your favorite drink?",
    "Would you rather never be able to laugh or never be able to cry?",
    "Would you rather know when you're going to die or know how you're going to die?",
    "Would you rather be able to perfectly mimic any voice or perfectly mimic any appearance?",
    "Would you rather live in a world where all your dreams come true or none of your nightmares come true?",
    "Would you rather have to always speak in rhyme or always speak in a whisper?",
    "Would you rather be able to instantly learn any skill or instantly earn $10 million?",
    "Would you rather be trapped in a horror movie or trapped in a rom-com?",
    "Would you rather have a rewind button for your words or a filter for your thoughts?",
    "Would you rather live in a perfect world with no suffering or live in a perfect world where you can't feel joy?",
    "Would you rather be famous for saving someone's life or famous for inventing something that changed the world?",
    "Would you rather have perfect memory or perfect imagination?",
    "Would you rather be able to see the future or change the past?",
    "Would you rather live without music or live without books?",
    "Would you rather be the funniest person in the room or the smartest person in the room?",
    "Would you rather have a time machine that only goes backward or one that only goes forward?",
    "Would you rather be able to talk to animals or be able to talk to deceased people?",
    "Would you rather live in a world where everyone is honest or everyone is kind?",
    "Would you rather have to always tell the truth or never be able to lie?",
    "Would you rather be able to make any dish taste amazing or never be hungry again?",
    "Would you rather have the ability to erase any memory or create any memory?",
    "Would you rather live without your phone or without your computer?",
    "Would you rather be born with the ability to fly or the ability to become invisible?",
    "Would you rather have to use crutches for the rest of your life or have to wear a giant foam suit?",
    "Would you rather be the only person who can see everyone's true colors or be the only person whose true colors no one can see?",
    "Would you rather live in a world where time moves 10x slower or 10x faster?",
    "Would you rather have the ability to perfectly predict the future or perfectly change the past?",
    "Would you rather be able to understand any animal or speak any language instantly?",
    "Would you rather live in a perfect simulation or in the real world?",
    "Would you rather have to restart your life every time you make a mistake or never be able to make a mistake?",
    "Would you rather be able to control the weather or control the emotions of everyone around you?",
    "Would you rather have unlimited wishes but only for others or 3 wishes but only for yourself?",
)

# --- Question of the Day (expanded from 6 to 50) ---
QUESTION_OF_THE_DAY_EXTENDED = (
    "What small thing made your day better this week?",
    "If you could master one skill instantly, what would it be?",
    "What's a movie or show you could watch over and over?",
    "What's the most interesting thing you've eaten recently?",
    "If you could have dinner with any fictional character, who would it be?",
    "What's one skill you think everyone should learn?",
    "What's your go-to comfort food?",
    "If you could live in any fictional universe, which one?",
    "What's something you're weirdly obsessed with?",
    "What's the most useless skill you have?",
    "If you could instantly become an expert in something, what would it be?",
    "What's a game you loved as a kid?",
    "What's something that always makes you laugh?",
    "If you won the lottery tomorrow, what's the first thing you'd do?",
    "What's your favorite way to spend a weekend?",
    "What's a book that changed your perspective?",
    "If you could have any superpower but only for 10 minutes a day, what would it be?",
    "What's something that's surprisingly expensive?",
    "What's the best piece of advice you've ever received?",
    "If you could only eat one cuisine for the rest of your life, what would it be?",
    "What's a movie that made you cry?",
    "What's something you thought was cool as a kid but think is lame now?",
    "If you could switch lives with one person for a day, who would it be?",
    "What's your strategy for a good first impression?",
    "What's something you're looking forward to this month?",
    "If you could learn to play any instrument instantly, which one?",
    "What's the weirdest food combination you secretly enjoy?",
    "What's a trend you wish would come back?",
    "If you could time travel to any decade, which one?",
    "What's something you always recommend to people?",
    "What's your guilty pleasure TV show?",
    "If you could have any job in the world with no financial constraints, what would it be?",
    "What's something you're terrible at but wish you were good at?",
    "If you had a pet dinosaur, what kind would it be?",
    "What's the most useful life hack you know?",
    "If you could only stream one artist forever, who would it be?",
    "What's something that immediately improves your mood?",
    "If you could design your perfect day, what would it look like?",
    "What's a skill you learned from the internet?",
    "If you could be famous for something, what would you want it to be?",
    "What's the most interesting place you've lived?",
    "If you could instantly visit any city in the world right now, where would you go?",
    "What's something you always do that confuses other people?",
    "If you could have the perfect conversation with anyone, who would it be?",
    "What's your favorite thing about [your main server]?",
    "If you could bring back any discontinued product, what would it be?",
    "What's a smell that instantly takes you back in time?",
    "If you could have a lifetime supply of one thing, what would it be?",
    "What's something you wish people asked you about more?",
    "If you could rewrite the ending of any movie, which one would you choose?",
    "What's the most adventurous thing you'd want to try someday?",
    "If you could be a background character in any story, which one?",
    "What's something you've recently changed your mind about?",
)
