from __future__ import annotations

from typing import Any

_CHARACTER_FIELDS: dict[str, list[str]] = {
    "vampire20th": [
        "name",
        "splat",
        "generation",
        "clan",
        "sire",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "appearance",
        "perception",
        "intelligence",
        "wits",
    ],
    "ghoul20th": [
        "name",
        "splat",
        "master",
        "generation",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "appearance",
        "perception",
        "intelligence",
        "wits",
    ],
    "human20th": [
        "name",
        "splat",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "appearance",
        "perception",
        "intelligence",
        "wits",
    ],
    "werewolf20th": [
        "name",
        "splat",
        "tribe",
        "auspice",
        "breed",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "appearance",
        "perception",
        "intelligence",
        "wits",
    ],
    "mage20th": [
        "name",
        "splat",
        "tradition",
        "essence",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "appearance",
        "perception",
        "intelligence",
        "wits",
    ],
    "changeling20th": [
        "name",
        "splat",
        "kith",
        "house",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "appearance",
        "perception",
        "intelligence",
        "wits",
    ],
    "wraith20th": [
        "name",
        "splat",
        "legion",
        "guild",
        "aspect",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "appearance",
        "perception",
        "intelligence",
        "wits",
    ],
    "demon20th": [
        "name",
        "splat",
        "agenda",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "appearance",
        "perception",
        "intelligence",
        "wits",
    ],
    "vampire5th": [
        "name",
        "splat",
        "clan",
        "generation",
        "blood_potency",
        "humanity",
        "concept",
        "sire",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "composure",
        "resolve",
        "intelligence",
        "wits",
    ],
    "hunter5th": [
        "name",
        "splat",
        "creed",
        "concept",
        "cell",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "composure",
        "resolve",
        "intelligence",
        "wits",
    ],
    "werewolf5th": [
        "name",
        "splat",
        "tribe",
        "auspice",
        "breed",
        "concept",
        "strength",
        "dexterity",
        "stamina",
        "presence",
        "manipulation",
        "composure",
        "resolve",
        "intelligence",
        "wits",
    ],
    "ghoul5th": [
        "name",
        "splat",
        "master",
        "concept",
        "blood_potency",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "composure",
        "resolve",
        "intelligence",
        "wits",
    ],
    "human5th": [
        "name",
        "splat",
        "concept",
        "strength",
        "dexterity",
        "stamina",
        "charisma",
        "manipulation",
        "composure",
        "resolve",
        "intelligence",
        "wits",
    ],
    "dragonborn": [
        "name",
        "splat",
        "ancestry",
        "concept",
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma",
    ],
    "dwarf": [
        "name",
        "splat",
        "subrace",
        "concept",
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma",
    ],
    "elf": [
        "name",
        "splat",
        "subrace",
        "concept",
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma",
    ],
    "gnome": [
        "name",
        "splat",
        "subrace",
        "concept",
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma",
    ],
    "half-elf": [
        "name",
        "splat",
        "ancestry",
        "concept",
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma",
    ],
    "half-orc": [
        "name",
        "splat",
        "ancestry",
        "concept",
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma",
    ],
    "halfling": [
        "name",
        "splat",
        "subrace",
        "concept",
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma",
    ],
    "human": [
        "name",
        "splat",
        "ancestry",
        "concept",
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma",
    ],
    "tiefling": [
        "name",
        "splat",
        "legacy",
        "concept",
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma",
    ],
}

# Back-compat lookup expected by older code
EDITION_DEFAULTS = {key: fields[:] for key, fields in _CHARACTER_FIELDS.items()}


def fields_for(splat: str) -> list[str]:
    return list(_CHARACTER_FIELDS.get(splat, ["name", "splat", "concept"]))


def sheet_template(splat: str) -> dict[str, Any]:
    return {field: "" for field in fields_for(splat)}
